# Generated by Django 3.1.14 on 2022-03-08 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0047_auto_20220302_1951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='terminal',
            options={'ordering': ('is_accepted',), 'permissions': (('view_terminalconfig', 'Can view terminal config'),), 'verbose_name': 'Terminals'},
        ),
    ]
