# Generated by Django 3.1.14 on 2022-03-08 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0048_auto_20220308_2045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Terminal task'},
        ),
        migrations.AlterModelOptions(
            name='terminal',
            options={'ordering': ('is_accepted',), 'permissions': (('view_terminalconfig', 'Can view terminal config'),), 'verbose_name': 'Terminal'},
        ),
    ]
