# Generated by Django 3.1.14 on 2022-03-09 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0049_auto_20220308_2056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'get_latest_by': 'date_created', 'verbose_name': 'Terminal status'},
        ),
    ]
