# Generated by Django 3.1.14 on 2022-03-08 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_superticket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvalrule',
            options={'default_permissions': [], 'verbose_name': 'Ticket flow approval rule'},
        ),
    ]
