# Generated by Django 3.1.14 on 2022-03-08 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_auto_20220308_1820'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'default_permissions': [], 'ordering': ('date_created',), 'permissions': [('view_comment', 'Can view comment'), ('add_comment', 'Can add comment')], 'verbose_name': 'Comment'},
        ),
    ]
