# Generated by Django 3.1.14 on 2022-03-08 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_auto_20220308_1825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='superticket',
            options={'default_permissions': [], 'permissions': [('add_superticket', 'Can add super ticket'), ('view_superticket', 'Can view super ticket'), ('change_superticket', 'Can change super ticket')], 'verbose_name': 'Super ticket'},
        ),
    ]
