# Generated by Django 3.1.14 on 2022-03-08 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0018_auto_20220308_1845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketassignee',
            options={'default_permissions': [], 'verbose_name': 'Ticket assignee'},
        ),
    ]
