# Generated by Django 3.1.14 on 2022-03-08 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0020_auto_20220308_1907'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketflow',
            options={'default_permissions': [], 'permissions': [('view_ticketflow', 'Can view ticket flow'), ('change_ticketflow', 'Can change ticket flow')], 'verbose_name': 'Ticket flow'},
        ),
    ]
