# Generated by Django 3.1.14 on 2022-03-08 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0022_auto_20220308_1911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketsession',
            options={'default_permissions': [], 'permissions': [('view_ticketsession', 'Can view ticket session'), ('add_ticketsession', 'Can add ticket session')], 'verbose_name': 'Ticket session relation'},
        ),
    ]
