# Generated by Django 3.1.14 on 2022-03-09 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0028_auto_20220309_1008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'default_permissions': [], 'ordering': ('-date_created',), 'permissions': {('view_ticket', 'Can view ticket'), ('add_ticket', 'Can add ticket')}, 'verbose_name': 'Ticket'},
        ),
    ]
