# Generated by Django 3.1.14 on 2022-03-08 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_auto_20220308_2009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setting',
            options={'default_permissions': [], 'permissions': [('change_basic', 'Can change basic setting'), ('change_email', 'Can change email setting'), ('change_auth', 'Can change authentication setting'), ('change_sms', 'Can change sms setting'), ('change_terminal_setting', 'Can change terminal setting'), ('change_security', 'Can change security setting'), ('change_clean', 'Can change clean setting'), ('change_other', 'Can change other setting')], 'verbose_name': 'System setting'},
        ),
    ]
