# Generated by Django 3.1.14 on 2022-03-07 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0004_auto_20211201_1901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menupermission',
            options={'default_permissions': [], 'permissions': [('view_dashboard', 'Can view dashboard'), ('view_consoleview', 'Can view console view'), ('view_auditview', 'Can view audit view'), ('view_workspaceview', 'Can view workspace view'), ('view_webterminal', 'Can view web terminal'), ('view_filemanagement', 'Can view file management')], 'verbose_name': 'Menu permission'},
        ),
    ]
