# Generated by Django 3.1.14 on 2022-03-08 06:35

from django.db import migrations


def delete_unused_permissions(apps, schema_editor):
    permission_model = apps.get_model('rbac', 'Permission')
    content_type_model = apps.get_model('rbac', 'ContentType')
    content_type_delete_required = [
        ('common', 'permission'),
    ]
    for app, model in content_type_delete_required:
        content_type_model.objects.filter(app_label=app, model=model).delete()

    permissions_delete_required = [
        ('rbac', 'menupermission', 'view_resourcestatistics'),
        ('rbac', 'menupermission', 'view_adminview'),
        ('rbac', 'menupermission', 'view_overview'),
        ('rbac', 'menupermission', 'view_userview'),
        ('rbac', 'menupermission', 'view_filemanager'),
        ('authentication', 'connectiontoken', 'delete_connectiontoken'),
        ('authentication', 'connectiontoken', 'change_connectiontoken'),
        ('authentication', 'superconnectiontoken', 'delete_superconnectiontoken'),
        ('authentication', 'superconnectiontoken', 'change_superconnectiontoken'),
        ('authentication', 'superconnectiontoken', 'view_superconnectiontoken'),
        ('authentication', 'ssotoken', 'view_ssotoken'),
        ('authentication', 'ssotoken', 'change_ssotoken'),
        ('authentication', 'ssotoken', 'delete_ssotoken'),
    ]
    for app, model, codename in permissions_delete_required:
        permission_model.objects.filter(
            codename=codename, content_type__model=model, content_type__app_label=app
        ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0006_auto_20220307_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menupermission',
            options={'default_permissions': [], 'permissions': [('view_dashboard', 'Can view dashboard'), ('view_consoleview', 'Can view console view'), ('view_auditview', 'Can view audit view'), ('view_workspaceview', 'Can view workspace view'), ('view_webterminal', 'Can view web terminal'), ('view_filemanagement', 'Can view file management')], 'verbose_name': 'Menu permission'},
        ),
        migrations.RunPython(delete_unused_permissions)
    ]
