# Generated by Django 3.1.14 on 2022-03-08 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_superconnectiontoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connectiontoken',
            options={'default_permissions': [('add_superconnectiontoken', 'Can add super connection token'), ('view_superconnectiontoken', 'Can view super connection token')], 'verbose_name': 'Connection token'},
        ),
    ]
