# Generated by Django 3.1.14 on 2022-03-08 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_auto_20220308_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='superconnectiontoken',
            options={'default_permissions': [], 'permissions': [('add_superconnectiontoken', 'Can add super connection token'), ('view_superconnectiontoken', 'Can view super connection token')], 'verbose_name': 'Super connection token'},
        ),
    ]
