# Generated by Django 3.1.14 on 2022-03-08 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_auto_20220308_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ssotoken',
            options={'default_permissions': [], 'permissions': [('add_ssotoken', 'Can add sso token')], 'verbose_name': 'SSO token'},
        ),
    ]
