# Generated by Django 3.1.14 on 2022-03-08 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_auto_20220308_1647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connectiontoken',
            options={'default_permissions': [], 'permissions': [('add_connectiontoken', 'Can add connection token'), ('view_connectiontoken', 'Can view connection token'), ('view_connectiontokensecret', 'Can view connection token secret')], 'verbose_name': 'Connection token'},
        ),
    ]
