# Generated by Django 3.1.14 on 2022-03-08 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_auto_20220308_1742'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesskey',
            options={'verbose_name': 'API key'},
        ),
    ]
