# Generated by Django 3.1.14 on 2022-03-09 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20210909_1946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemmsgsubscription',
            options={'verbose_name': 'System msg subscription'},
        ),
    ]
